DELETE
FROM bookings;
DELETE
FROM items;
DELETE
FROM users;

ALTER TABLE bookings
    ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE items
    ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE users
    ALTER COLUMN ID RESTART WITH 1;