DELETE
FROM comments;
DELETE
FROM bookings;
DELETE
FROM items;
DELETE
FROM requests;
DELETE
FROM users;
DELETE
FROM users;

ALTER TABLE comments
    ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE bookings
    ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE items
    ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE requests
    ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE users
    ALTER COLUMN ID RESTART WITH 1;
