DROP TABLE IF EXISTS comments, bookings, items, requests, users;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    description  VARCHAR(512)                            NOT NULL,
    requestor_id BIGINT                                  NOT NULL REFERENCES users ON DELETE CASCADE,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    is_available BOOL                                    NOT NULL,
    owner_id     BIGINT                                  NOT NULL REFERENCES users,
    request_id   BIGINT REFERENCES requests
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id    BIGINT                                  NOT NULL REFERENCES items ON DELETE CASCADE,
    booker_id  BIGINT                                  NOT NULL REFERENCES users ON DELETE CASCADE,
    status     VARCHAR(255)                            NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    text      VARCHAR(512)                            NOT NULL,
    item_id   BIGINT                                  NOT NULL REFERENCES items ON DELETE CASCADE,
    author_id BIGINT                                  NOT NULL REFERENCES users ON DELETE CASCADE,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);
